services:
  dashboard:
    image: dashboard
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - ./:/DS-6600
    networks:
      - dbnetwork

  postgres:
    image: postgres
    
    #Question 1: What environment variables should be used to configure the database?
    env_file:
      - .env

    #Question 2: Does the software have a port (inside the container) it runs on by default?
    ports:
      - "5432:5432"

    #Question 3: What folder inside the container stores the data you need to save?
    volumes:
      - postgresdata:/var/lib/postgresql/18/docker
    
    networks:
      - dbnetwork
  

  mysql:
    image: mysql

    #Question 1: What environment variables should be used to configure the database?
    env_file:
      - .env

    #Question 2: Does the software have a port (inside the container) it runs on by default?
    ports:
      - "3306:3306"

    #Question 3: What folder inside the container stores the data you need to save?
    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      - dbnetwork
  
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork


volumes:
  postgresdata:
  mysqldata:
  mongodata:

networks:
  dbnetwork:

